
# server:
#   port: 9001

spring:
  application:
    name: auth-service

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root
