
# server:
#   port: 8080

spring:
  application:
    name: gateway

server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: poll-service
          uri: http://localhost:8082
          predicates:
            - Path=/polls/**
        - id: vote-service
          uri: http://localhost:8083
          predicates:
            - Path=/votes/**
