
# server:
#   port: 9002

spring:
  application:
    name: poll-service

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polldb
    username: root
    password: root
