
# server:
#   port: 9003

spring:
  application:
    name: vote-service

server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/votedb
    username: root
    password: root
