
server:
  port: 9002
spring:
  datasource:
    url: jdbc:h2:mem:polldb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
