# server:
#   port: 8888

# spring:
#   application:
#     name: config-server
#   cloud:
#     config:
#       server:
#         git:
#           uri: https://github.com/sanskar-1802/config-repo.git
#           default-label: main

server:
  port: 8888   # Config Server runs on port 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Dell/Downloads/click2vote-starter/config-repo  # local repo path
          default-label: main 
          clone-on-start: true
