server:
  port: 8085
  max-http-header-size: 40 KB

spring:
  main:
    web-application-type: reactive   # force reactive mode

  cloud:
    gateway:
      routes:
        # Auth Service
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        
        # Poll Service
        - id: poll-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/polls/**
        
        # Vote Service
        - id: vote-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/votes/**
          filters:
            - StripPrefix=1  
        
        # Root redirect to Auth Service (optional)
        - id: root
          uri: http://localhost:8081
          predicates:
            - Path=/
        
        # Fallback route for undefined paths
        - id: fallback
          uri: "http://localhost:8085/fallback"
          predicates:
            - Path=/**

